FROM golang:1.14.13-alpine3.12 as builder
ARG CLI_VERSION="trunk"
ENV GH_CLI_VERSION="$CLI_VERSION"
RUN apk update && \
    apk add make git gcc libc-dev && \
    git clone --depth 1 --branch $GH_CLI_VERSION https://github.com/cli/cli.git /go/src/gh-cli && \
    cd /go/src/gh-cli && \
    make

FROM node:15-alpine

RUN apk update && apk add git openssh

COPY --from=builder /go/src/gh-cli/bin/gh /usr/local/bin/

# sudo using su-exec
RUN set -ex; \
    apk add --no-cache su-exec && \
    chmod a+s /sbin/su-exec &&\
    echo "#!/bin/sh" >> /usr/bin/sudo &&\
    echo '/sbin/su-exec root "$@"' >> /usr/bin/sudo &&\
    chmod a+x /usr/bin/sudo
# make directory for source code
RUN mkdir -p /usr/src && \
    chmod -R 777 /usr/src


ENTRYPOINT ["/bin/sh"]
